### ISSUE TITLE
links para programação funcional

### ISSUE THREAD

**Issue by luizbills** [fabiane/mentoria#2]
Recomendo esses 3 links:

- Esse ótimo livro dá uma boa introdução ao mundo da programação funcional: https://drboolean.gitbooks.io/mostly-adequate-guide-old/content/

- Esse artigo é maravilhoso (te introduz o conceito de `combinators`): http://raganwald.com/2015/02/13/functional-quantum-electrodynamics.html 

- Esse livro também muito bom (ainda estou terminando de lê-lo): https://leanpub.com/javascriptallongesix/read

---

Sou bem iniciante em programação funcional, a única coisa que posso te falar é que aprender programação funcional é como aprender a programar novamente kkk é outro mundo.

**Comment by fabiane** [comment]
Agradeço Luiz!

**Comment by luizbills** [comment]
Ah esqueci de linkar esse cara aqui https://medium.com/@joelthoms
Os artigos dele são incriveis.
